# Site settings
title: Andrzej Jarzyna CV
email: andrew.jarzyna@gmail.com
description: "CV of Andrzej JArzyna"
baseurl: ""
url: "http://andrzejCV.github.io"
github_username:  jerzyn

# Build settings
markdown: kramdown
permalink: pretty
gems:
- jekyll-compass
