# Site settings
title: Andrzej Jarzyna
email: andrew.jarzyna@gmail.com
description: "CV of Andrzej JArzyna"
baseurl: ""
url: "http://jerzyn.github.io"
github_username: jerzyn

# Build settings
markdown: kramdown
permalink: pretty
gems:
- jekyll-compass
